### ISSUE TITLE
django-taggit support

### ISSUE THREAD

**Issue by ArchitectOnNet** [iommirocks/iommi#339]
Hallo and thank you for the awesome framework. 

I'm trying to use django-taggit in one of my model fields by setting the field as _TaggableManager_. 

Once I do that I get the following error on the view:
AssertionError at /contacts/mini/
No factory for TaggableManager. Register a factory with register_factory or register_column_factory, you can also register one that returns None to not handle this field type

How can I integrate django-taggit in iommi? Alternatively, how could I return None from register_factory  to avoid the error? 

Thanks in advance

**Comment by ArchitectOnNet** [comment]
Coming back with a workaround:

in models.py
`register_factory(
		GenericRelation,
		factory=None
	)
register_factory(
        TaggableManager,
		factory=None
    )
`

in views.py:
```
Table(
...
	columns=dict(
		#number__cell__value=lambda row, **_: f"{row.number:04d}",
		tags__cell__value=lambda row, **_: f"{ ' | '.join( list(row.tags.values_list('name', flat= True ))) }"  ,

	)
...
)
```

Registrations seem really cool. I need to dig more into that for a more pythonic solution.

Any input on the subject would be much appreciated.

**Comment by jlubcke** [comment]
If you want to go the path of registering a factory, you can re-use the existing for many to many:
