### ISSUE TITLE
Getting Started Documentation issues.

### ISSUE THREAD

**Issue by MickeyM79** [iommirocks/iommi#386]
I'm kicking the tires(picks) of iommi for the first time.  In doing so, I'm following the Getting Started section and ran into some things that could trip up someone not familiar with Django.  I'll outline the issues here and make a pull request later after I finish going through the documentation, unless I am just doing something wrong.

- Section 2 should be about creating a basic model(s), as when you try to use the Album model it doesn't exist on a new installation. 
- The current Section 2 (Your first form) needs to have an include to the model created such that Album is defined.
- Section 3 (Your first table) needs to have an include to the model such that Album is defined.
- Section 4 (Your first page) needs to have an include to the model such that Artist is defined.

**Comment by boxed** [comment]
hmm. you've very right. The tutorial has that kind of note at the top: https://docs.iommi.rocks/en/latest/tutorial.html

**Comment by MickeyM79** [comment]
Does it make more sense to just copy the model info to the getting started section, or just point the getting started section to the tutorial?  I haven't read through the tutorial yet, so I'm not sure what all is in it.  Either way.. I don't care to update and send a PR once it's determined how it should look.

**Comment by boxed** [comment]
yea... the tutorial is written way more recent than the Getting Started guide, so that probably shows :P

Please keep the feedback coming!

**Comment by boxed** [comment]
I have made some changes to the getting started page to improve this.
