### ISSUE TITLE
table__query__form__actions__submit__display_name in czech (maybe other languages?)

### ISSUE THREAD

**Issue by berycz** [iommirocks/iommi#401]
In `query.py` you have filter submit button with `display_name=gettext('Filter')`, which gets translated in czech (from django translates) as `Filtr` - that is noun though and this should be verb (CZ: imperative `Filtruj` or infinitive `Filtrovat`)
Might be better to make it `display_name=gettext('Submit filter')` and translate it even for EN
I might be wrong but I'd also guess that iommi translates override the ones from django based on INSTALLED_APPS order?

**Comment by boxed** [comment]
Probably broken in Swedish and German too.

**Comment by yurkobb** [comment]
As an alternative, [pgettext](https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#contextual-markers) may be used.

**Comment by berycz** [comment]
oh btw, I had similar problem with the `freetext_search__display_name` where `Search` has cz translate `Hledat` (verb infinitive) and I need rather something like `Hledané slovo` (=`Search term`)
