### ISSUE TITLE
CharField with choices not well supported (probably also numeric fields with choices)

### ISSUE THREAD

**Issue by berycz** [iommirocks/iommi#407]
When I have model fields as `CharField` with `choices` and I use `auto__model`

1. in the filter form I get text-input instead of select2, then I have to define
```py
query__form__fields__foo = Field.choice(choices=[...], choice_display_name_formatter=lambda choice, **_: ...)
```
2. in the table columns I get raw values instead of the "display names", then I have to define
```py
columns__foo__cell__value = lambda row, **_: ...
```

would be nice to get that out of the box :)

**Comment by berycz** [comment]
I may be wrong, the 1. seems to actually work now, but the 2. not for some reason

**Comment by leethobbit** [comment]
Going to add a comment here as this seems to be the same issue and I was asked to open an issue by boxed.

**ISSUE: When using auto__model to display fields in a Table or Form, and that field is a choice field, it should display the human readable or "display values" by default. Instead, it is displaying the actual value.**

I am noticing this specifically with CharField - I do not current do choices with any other field type.

Thank you!
