### ISSUE TITLE
table.Column.boolean check mark

### ISSUE THREAD

**Issue by berycz** [iommirocks/iommi#508]
You use the font-awesome check icon in `table.Column.boolean @with_defaults` 
```py
cell__format=lambda value, **_: mark_safe('<i class="fa fa-check" title="Yes"></i>') if value else '',
```

I believe it might be better to get rid of the dependency and maybe use any of the utf-8 characters ✔ ✅ ✔ ☑ .
And use the `fa-check` only in `style_font_awesome_4.py`
```py
Column__shortcuts__boolean__cell__format=lambda value, **_: mark_safe('<i class="fa fa-check" title="Yes"></i>') if value else ''
```

Then in `style_bootstrap_icons.py` I'd probably use the `bi-check-lg` with ` fs-3`
```py
Column__shortcuts__boolean__cell__format=lambda value, **_: mark_safe('<i class="bi bi-check-lg fs-3"></i>') if value else ''
```

**Comment by boxed** [comment]
Agreed
