### ISSUE TITLE
Table use query with multiple objects

### ISSUE THREAD

**Issue by deepaktrama** [iommirocks/iommi#513]
Can the table use fields from multiple related models like display album.artist.name and is there an example of this in the docs?

Thank you.

**Comment by boxed** [comment]
Yes, do this: `auto__include=['album__artist__name']` for example.

**Comment by deepaktrama** [comment]
yes, I confirm that the above works! 
is it possible to run a function or python operation to beautify the string for example below.

 auto__include=['album__artist__name[0:3]'] # python slice to get first 3 characters
 auto__include=['beautify(album__artist__name)'] # custom function

I understand that you are replacing the . operator with __, are there some docs on this convention and practice?

**Comment by boxed** [comment]
You want to specify a cell formatter. https://docs.iommi.rocks/en/latest/cookbook_tables.html#how-do-i-customize-the-rendering-of-a-table

And for the dunder stuff maybe https://docs.iommi.rocks/en/latest/philosophy.html
