### ISSUE TITLE
Problems with EditTable when using column filter and column edit together

### ISSUE THREAD

**Issue by hsuan81** [iommirocks/iommi#527]
I made an EditTable with one 'name' column editable and filtering on 'year' column.
`EditTable(
        title="Song",
        auto__model=Album,
        page_size=5,
        columns__name__edit__include=True,
        columns__year__filter__include=True,
    )`

I encountered two problems:
1. When clicking filter button, a csrf token missing error occurred.
2. When clicking save button after editing data, either adding a new row or updating the name column of existing data, the button seemed losing function that it didn't save the data.

Has anyone come across these problems before? Or are there any workarounds I can use?

**Comment by boxed** [comment]
This is fixed in #525. This will be new major version as `columns__name__edit__include` will be changed to `columns__name__filter__include`, but that should be the only change needed.

**Comment by boxed** [comment]
7.0.0 is released now with this fix.
