### ISSUE TITLE
AssertionError:No exception message supplied

### ISSUE THREAD

**Issue by FrankFang0813** [iommirocks/iommi#538]
Hi, I have a Error Message, I have no idea.
I use `ii.Field(editable=False)`, then got this error.
But `ii.Field(editable=True)` is OK

This is my code:
```py
columns__miti_price_1=dict(
            after=11,
            render_column=True,
            display_name="Price",
            group="AAAA",
            field=ii.Field(required=False),
        )
```

Thank You

**Comment by boxed** [comment]
You forgot to post the error

**Comment by boxed** [comment]
Please reopen with the error message if you have the problem still.
