### ISSUE TITLE
Question about fbv return Page directly.

### ISSUE THREAD

**Issue by ivkus** [iommirocks/iommi#541]
django function based views should return a django.http.HTTPResponse, but in the [cookbook: How do I specify the context used when a Template is rendered?](https://docs.iommi.rocks/en/latest/cookbook_parts_pages.html#how-do-i-specify-the-context-used-when-a-template-is-rendered), a Page return directly.

I could not find a way to convert  a Page to HTTPResponse. can someone explain it in detail?

**Comment by boxed** [comment]
The iommi middleware will intercept any iommi type and do the bind and render to response calls. The code in the documentation will work.

**Comment by ivkus** [comment]
thank you.
I forget to check the middleware.
besides, this is a good project. i learned much from here. thank you again!
