### ISSUE TITLE
[Bug] Iommi framework unable to parse styles with name containing 2 underscores "__"

### ISSUE THREAD

**Issue by akhileshThapliyal** [iommirocks/iommi#555]
When I use a class with a name containing 2 underscores "__" the framework can't parse the class name. For instance, the below class values don't work dm-pagination__item, dm-pagination__item and dm-pagination__link

# Styles

```
Paginator__attrs__class={
    'dm-page': True
},
Paginator__container__attrs__class={
    'dm-pagination d-flex': True
},
Paginator__item__attrs__class={
    'dm-pagination__item': True
},
Paginator__active_item__attrs__class={
    'dm-pagination__item': True
},
Paginator__link__attrs__class={
    'dm-pagination__link': True
}
```

# DOM

![image](https://github.com/user-attachments/assets/ab1d8a4d-db5d-4129-991e-9ecfb404613c)

**Comment by boxed** [comment]
Fixed by https://github.com/iommirocks/iommi/pull/559
