### ISSUE TITLE
Cannot set classes with a callable if the contain `__` in the classname.

### ISSUE THREAD

**Issue by apollo13** [iommirocks/iommi#579]
While trying to create a style for patternfly6 which uses class names like `pf-v6-c-table__sort` I ran into the issue that I cannot set this to a callable:
```py
my_style = Style(
    base,
    Column=dict(
        header__attrs__class={
            "yolo": lambda **_: False,
            "bogo__sort": lambda **_: False,
        }
    ),
)
```

Attaching that style to a table yields: `class="bogo__sort first_column iommi_sort_header subheader"`. The problem seems to be that `iommi.attrs.render_class` doesn't evaluate the callable. Inserting
```py
print(items(flatten(class_dict)))
```

into that function yields:
```
dict_items([('sorted', False), ('descending', False), ('ascending', False), ('first_column', True), ('subheader', True), ('iommi_sort_header', True), ('yolo', False), ('bogo__sort', <function <lambda> at 0x7fbd89d62a20>)])
```

`yolo` apparently got evaluated higher up the chain already.

**Comment by boxed** [comment]
Fixed in #581
