### ISSUE TITLE
Trouble with Explicit Table Creation of ManyToMany Fields

### ISSUE THREAD

**Issue by thoward27** [iommirocks/iommi#599]
Thank you to the fine maintainers of this lovely piece of software. 

I have been having a very tough time getting a ManyToMany column to render in an explicitly created table.

It works perfectly when I use the auto-creation method. I've tried tracing what that approach is doing, but I am at a loss.

Sample of my models

```python
class Fixture(models.Model):
    """A fixture between two or more players."""

    users = models.ManyToManyField(to="games.User", through="games.Rank")

class User(AbstractUser):
    """A user of the system."""

    score = models.PositiveIntegerField(default=settings.DEFAULT_SCORE)
```

Here's what works

```py
class FixturePage(iommi.Page):
    fixtures = iommi.Table(auto__model=models.Fixture)
```

It renders a table, with the `users` column as a list of strings joined by a comma (ie `user1, user1`)

However, when I try this:

```py
class FixtureTable(iommi.Table):
    users = iommi.Column()

    class Meta:
        rows = models.Fixture.objects.all()
        title = "Fixtures"
        page_size = 30
```

I get `games.User.None` for every row.

I've tried a number of variations on the failing case, but I can't seem to put together what I am missing.

If anyone can help me wrap my head around this, it would be greatly appreciated!

**Comment by boxed** [comment]
This is a bit of Django leaking through. So in this case you probably do want to use the `auto` machinery, but otherwise you can look at `Column.many_to_many` to see what it does. This line is the most significant:

```py
        cell__format=lambda value, **_: ', '.join(['%s' % x for x in value.all()]),
```

**Comment by thoward27** [comment]
Thank you for the tip @boxed! 

Here's how I ended up getting this to work:

```python
class FixtureTable(iommi.Table):
    users = iommi.Column.many_to_many(
        models.Fixture.users.field,
        filter__call_target__attribute="choice",
        filter__include=True,
    )
```

The most challenging for me was figuring out the proper argument to the `many_to_many` column.
